// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-TsnKfB_ZHVJlZszIeVRxYakWPW1rjFI',
    appId: '1:477170291357:web:6f83b63cc22f159839fa74',
    messagingSenderId: '477170291357',
    projectId: 'chatapp-b6775',
    authDomain: 'chatapp-b6775.firebaseapp.com',
    storageBucket: 'chatapp-b6775.firebasestorage.app',
    measurementId: 'G-MCVHWVYPFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIuw5I3cCbVgEnvHC9UfrCSg7SwjCXKYw',
    appId: '1:477170291357:android:9a3a92398b17e7d339fa74',
    messagingSenderId: '477170291357',
    projectId: 'chatapp-b6775',
    storageBucket: 'chatapp-b6775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHbQDE-5xv3hTD0X7o4VizkPQ-YzK7n5Q',
    appId: '1:477170291357:ios:ca0c2b443ed9c25d39fa74',
    messagingSenderId: '477170291357',
    projectId: 'chatapp-b6775',
    storageBucket: 'chatapp-b6775.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHbQDE-5xv3hTD0X7o4VizkPQ-YzK7n5Q',
    appId: '1:477170291357:ios:ca0c2b443ed9c25d39fa74',
    messagingSenderId: '477170291357',
    projectId: 'chatapp-b6775',
    storageBucket: 'chatapp-b6775.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-TsnKfB_ZHVJlZszIeVRxYakWPW1rjFI',
    appId: '1:477170291357:web:6b8dabbafae5599b39fa74',
    messagingSenderId: '477170291357',
    projectId: 'chatapp-b6775',
    authDomain: 'chatapp-b6775.firebaseapp.com',
    storageBucket: 'chatapp-b6775.firebasestorage.app',
    measurementId: 'G-9L6HRSBN6F',
  );
}
